service: ${env:SERVICE_NAME, 'nestjs-serverless'}

frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    port: 3000
    noPrependStageInUrl: true
    reloadHandler: true
  bundle:
    sourcemaps: true
    tsConfig: './tsconfig.bundle.json'
    caching: false
    linting: true
    minifyOptions:
      keepNames: true
    ignorePackages:
      - '@nestjs/microservices'
      - '@nestjs/microservices/microservices-module'
      - '@nestjs/websockets/socket-module'
      - 'cache-manager'
      - 'class-transformer/storage'
      - '@apollo/federation'
      - '@apollo/subgraph'
      - '@apollo/subgraph/dist/directives'
      - 'apollo-server-fastify'
    forceExclude:
      - 'aws-sdk'

provider:
  name: aws
  stage: local
  runtime: nodejs18.x
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
