name: Typecheck

on:
  workflow_call:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: |
          # Install dependencies based on the lockfile and the package manager
          if [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          elif [ -f "package-lock.json" ]; then
            npm install
          elif [ -f "pnpm-lock.yaml" ]; then
            pnpm install
          else
            echo "No lockfile found. Please add a lockfile to your repository."
            exit 1
          fi

      - name: Run type-check validation
        run: npm run type-check --if-present
